import { Tile } from "./model.js";

let player = null;
let board = null;
let difficulty = 5;
let time = 0;
let timeInterval = null;
let currentAttempt = null;
let currentDifficulty = null;

const TILE_TYPES = {
  EMPTY: "empty",
  BRIDGE: "bridge",
  MOUNTAIN: "mountain",
  OASIS: "oasis",
  STRAIGHT_RAIL: "straight_rail",
  CURVE_RAIL: "curve_rail",
  BRIDGE_RAIL: "bridge_rail",
  MOUNTAIN_RAIL: "mountain_rail",
};

const LEVEL_TEMPLATES = {
  5: {
    "Humble Beginnings": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.OASIS),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Meadowlink Junction": [
      [
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Riverside Route": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
      ],
    ],
    "Forest Crossing": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Valley Vista": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
  },
  7: {
    "Mountain Pass Maze": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Desert Oasis Loop": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
      ],
      [
        Tile.createBasic(TILE_TYPES.MOUNTAIN),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Coastal Challenge": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
      ],
      [
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Mystic Marshlands": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 270),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
    "Royal Circuit": [
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.BRIDGE, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 90),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.OASIS),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.MOUNTAIN, 180),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.BRIDGE),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
      [
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
        Tile.createBasic(TILE_TYPES.EMPTY),
      ],
    ],
  },
};

const LEVEL_NAMES = Object.fromEntries(
  Object.entries(LEVEL_TEMPLATES).map(([key, value]) => [
    key,
    Object.keys(value),
  ])
);

const TILE_CONNECTIONS = {
  empty: {
    0: ["top", "right", "bottom", "left"],
    90: ["top", "right", "bottom", "left"],
    180: ["top", "right", "bottom", "left"],
    270: ["top", "right", "bottom", "left"],
  },
  straight_rail: {
    0: ["top", "bottom"],
    90: ["left", "right"],
    180: ["top", "bottom"],
    270: ["left", "right"],
  },
  curve_rail: {
    0: ["bottom", "right"],
    90: ["left", "bottom"],
    180: ["top", "left"],
    270: ["right", "top"],
  },
  bridge_rail: {
    0: ["top", "bottom"],
    90: ["left", "right"],
    180: ["top", "bottom"],
    270: ["left", "right"],
  },
  bridge: {
    0: ["top", "bottom"],
    90: ["left", "right"],
    180: ["top", "bottom"],
    270: ["left", "right"],
  },
  mountain_rail: {
    0: ["bottom", "right"],
    90: ["left", "bottom"],
    180: ["top", "left"],
    270: ["right", "top"],
  },
  mountain: {
    0: ["bottom", "right"],
    90: ["left", "bottom"],
    180: ["top", "left"],
    270: ["right", "top"],
  },
};

export default {
  player,
  board,
  difficulty,
  time,
  timeInterval,
  currentAttempt,
  currentDifficulty,
  TILE_TYPES,
  LEVEL_NAMES,
  LEVEL_TEMPLATES,
  TILE_CONNECTIONS,
};
